datos<-read.table("./test6.csv", header = TRUE, sep = ";")
x = c(1,2,3,4,5,6,7,8,9,10)
orders = c(mean(datos$O0),mean(datos$O1),mean(datos$O2),mean(datos$O3),mean(datos$O4),mean(datos$O5),mean(datos$O6),mean(datos$O7),mean(datos$O8),mean(datos$O9))
plot(datos$Cost_km,orders, log = "",type="o", main = "Relación entre órdenes atendidas y coste km", xlab = "Coste del kilómetro", ylab = "Órdenes atendidas",col = "red", lty = 1, pch=19)
plot(x,orders, log = "",type="o", main = "Relación entre órdenes atendidas en escala log", xlab = "log(Coste del kilómetro)", ylab = "Órdenes atendidas",col = "red", lty = 1, pch=19)

dias = c(0,1,2,3)
prop_coste_2 = c(mean(datos$P00),mean(datos$P10),mean(datos$P20),mean(datos$P30))
prop_coste_4 = c(mean(datos$P01),mean(datos$P11),mean(datos$P21),mean(datos$P31))
prop_coste_8 = c(mean(datos$P02),mean(datos$P12),mean(datos$P22),mean(datos$P32))
prop_coste_16 = c(mean(datos$P03),mean(datos$P13),mean(datos$P23),mean(datos$P33))
prop_coste_32 = c(mean(datos$P04),mean(datos$P14),mean(datos$P24),mean(datos$P34))
prop_coste_64 = c(mean(datos$P05),mean(datos$P15),mean(datos$P25),mean(datos$P35))
prop_coste_128 = c(mean(datos$P06),mean(datos$P16),mean(datos$P26),mean(datos$P36))
prop_coste_256 = c(mean(datos$P07),mean(datos$P17),mean(datos$P27),mean(datos$P37))
prop_coste_512 = c(mean(datos$P08),mean(datos$P18),mean(datos$P28),mean(datos$P38))
prop_coste_1024 = c(mean(datos$P09),mean(datos$P19),mean(datos$P29),mean(datos$P39))
plot(dias,prop_coste_2,ylab = "Proporcion órdenes atendidas", xlab = "Antigüedad de la orden (días)", type = 'b', col = "red", ylim=c(0,1.1), pch=19, main = "Proporción órdenes atendidas")
lines(dias,prop_coste_4,type = 'b', col = "green",pch=19)
lines(dias,prop_coste_8,type = 'b', col = "blue",pch=19)
lines(dias,prop_coste_16,type = 'b', col = "yellow",pch=19)
lines(dias,prop_coste_32,type = 'b', col = "pink",pch=19)
lines(dias,prop_coste_64,type = 'b', col = "orange",pch=19)
lines(dias,prop_coste_128,type = 'b', col = "black",pch=19)
lines(dias,prop_coste_256,type = 'b', col = "brown",pch=19)
lines(dias,prop_coste_512,type = 'b', col = "purple",pch=19)
lines(dias,prop_coste_1024,type = 'b', col = "grey",pch=19)
legend(2.5, 1.1, legend=c("Cost 2", "Cost 4", "Cost 8", "Cost 16", "Cost 32", "Cost 64", "Cost 128", "Cost 256", "Cost 512", "Cost 1024"),
       col=c("red", "green", "blue","yellow", "pink", "orange", "black", "brown", "purple", "grey"), lty=1, cex = 0.5)


