datos1<-read.table("./test5_benefits_1.csv", header = TRUE)
datos2<-read.table("./test5_benefits_2.csv", header = TRUE)
datos3<-read.table("./test5_distances_1.csv", header = TRUE)
datos4<-read.table("./test5_distances_2.csv", header = TRUE)
boxplot(datos1$X1,datos2$X2, names = c("Mutliplicidad 1", "Multiplicidad 2"),main = "Beneficio obtenido")
boxplot(datos3$Y1,datos4$Y2, names = c("Mutliplicidad 1", "Multiplicidad 2"),main = "Kilómetros recorridos")
summary(datos1$X1)
sd(datos1$X1, na.rm=TRUE)
summary(datos2$X2)
sd(datos2$X2, na.rm=TRUE)
summary(datos3$Y1)
sd(datos3$Y1, na.rm=TRUE)
summary(datos4$Y2)
sd(datos4$Y2, na.rm=TRUE)
t.test(datos1$X1,datos2$X2,mu = 1000, paired = TRUE)
t.test(datos3$Y1,datos4$Y2, mu = 1000, paired = TRUE)